# Generated by Django 4.2.5 on 2023-09-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_buyer',
            new_name='is_company',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_executant',
            new_name='is_user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
    ]
